# model
model_name_or_path: /mnt/workspace/lixiangyu/Meta-Llama-3-8B-Instruct

# method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj

# dataset
dataset: citation_train
template: llama3
cutoff_len: 4096
max_samples: 85652
val_size: 0.1
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: /mnt/workspace/lixiangyu/cit/saves/Llama-3-8B-Instruct/lora/sft-citation
logging_steps: 50
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

# eval
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500
